name: Publish-Github-Pages

on:
  push:
    branches:
      - main

jobs:
  PublishDocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poetry-version: ["1.5.1"]

    steps:
      - uses: actions/checkout@v3
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCSITE_TOKEN }}
        with:
          source-directory: 'docs'
          destination-github-username: 'thorrester'
          destination-repository-name: 'opsml-docsite'
          user-email: ${{ secrets.USER_EMAIL }}
          target-branch: main
          target-directory: docs