name: Publish-Github-Pages

on:
  push:
    branches:
      - main

jobs:
  PublishDocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poetry-version: ["1.5.1"]

    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://thorrester:${{ secrets.DOCSITE_TOKEN }}@github.com/thorrester/opsml-docsite.git docsite
          rm -r docsite/docs
          cp -r docs docsite/docs
          cd docsite
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic Documentation Update"
          git push docsite main
